### ISSUE TITLE
Binary Search returns option, however it may be useful to return nearest non-overlapping index

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/utils#104]
I need a way to determine the closest non-overlapping region in case there is no overlapping region.

**Comment by fnothaft** [comment]
Do you need the closest _index_, or is the closest record OK?

**Comment by heuermh** [comment]
Either way it should probably be a separate method

**Comment by devin-petersohn** [comment]
I will create a pull request for my fix to this. We need the closest record, but I don't think we should change the way the current implementation works.

**Comment by fnothaft** [comment]
Sounds good. I agree with @heuermh, BTW.
