### ISSUE TITLE
Thread unsafe variable causing undefined/irregular behavior for ADAM

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/utils#114]
I think we should revert this back. Here are the lines in question: [Thread unsafe variable declaration](https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala#L123), [Use in the get method](https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala#L439). Once I took this out I no longer got the failures.

**Comment by fnothaft** [comment]
I don't think this is the correct solution. The correct solution should be to do the copy of the class, no?

**Comment by devin-petersohn** [comment]
Yes, I like that solution better.
