### ISSUE TITLE
Initializing Metrics across project

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/utils#117]
I am trying to initialize metrics upon project start using Metrics.initialize(sc). However, I can not access it in other packages or files. Reinitialization will result in loss of past metrics. How can I initialize metrics once such that I can access it everywhere?

**Comment by heuermh** [comment]
Each Metrics is thread-local

https://github.com/bigdatagenomics/utils/blob/master/utils-metrics/src/main/scala/org/bdgenomics/utils/instrumentation/Metrics.scala#L96

so we initialize it in main

https://github.com/bigdatagenomics/utils/blob/master/utils-cli/src/main/scala/org/bdgenomics/utils/cli/BDGCommand.scala#L68

or here, for `adam-shell`

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/ADAMShell.scala#L343

What do you mean by not being able to access it in other packages?

**Comment by heuermh** [comment]
Hello @akmorrow13, is this still an issue?

**Comment by akmorrow13** [comment]
This is no longer an issue for mango, we removed the metrics code from the browser.

**Comment by heuermh** [comment]
Thank you!
