### ISSUE TITLE
Remove AWS dependency

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/utils#41]
See discussion in https://github.com/bigdatagenomics/adam/pull/690.

We depend on the AWS SDK for the Serializable AWS credentials. I believe that this is dead code.

**Comment by heuermh** [comment]
re: https://github.com/bigdatagenomics/adam/pull/690#issuecomment-107751949

Taking a quick look at this, it looks generally useful and as such might still make sense in a utils module.  Was the old S3 Parquet loader you refer to replaced by something else?

**Comment by fnothaft** [comment]
What is useful about this? The AWS SDK? Any downstream project can just depend on AWS independently.

**Comment by heuermh** [comment]
I'm seeing classes CredentialsProperties, S3ByteAccess, S3FileLocator, SerializableAWSCredentials.  Even if no longer used in ADAM they seem generally useful.

**Comment by fnothaft** [comment]
Ah, gotcha. I'm not much of a fan of letting dead code that adds a dependency stay in the repository. If we need the code at a later date, we can always revert the commit that removed it.

**Comment by heuermh** [comment]
ok, then there's just the binary compatibility argument, which I'm not sure applies to these 0.x-versioned projects yet :)

**Comment by fnothaft** [comment]
Yeah, we're not concerned about that until 1.x.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/utils/commit/2b4c15401afae8b82771a218b96f3b6b81cf6061.
