### ISSUE TITLE
Make SparkFunSuite public so it can be re-used in other projects

### ISSUE THREAD

**Issue by chris-zen** [bigdatagenomics/utils#43]
This trait is very useful for testing and could be re-used in other projects as well.
Being in the *tests* folder makes it not to be exported to the maven jar and then not available to other projects.

Possible solutions:
- Move it to *src* of *utils-misc*
- Move to another package called *utils-testing*
- Create and export a jar for the *tests* code in *utils-misc*

**Comment by fnothaft** [comment]
Hi @chris-zen! I had totally missed this issue when you opened it. My apologies for the very slow response.

The `SparkFunSuite` trait is public; we use it in several downstream projects, e.g. https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/test/scala/org/bdgenomics/adam/util/ADAMFunSuite.scala. However, it isn't packaged as the main JAR; instead it is part of the test JAR. You can get this in Maven as:

```
<dependency>
  <groupId>org.bdgenomics.utils</groupId>
  <artifactId>utils-misc_2.10</artifactId>
  <version>0.2.2</version>
  <type>test-jar</type>
  <scope>test</scope>
</dependency>
```

Let me know if you still have any problems using the trait!

**Comment by chris-zen** [comment]
@fnothaft, thanks a lot for the information.
