### ISSUE TITLE
publish a spark 1.5 version

### ISSUE THREAD

**Issue by calvertj** [bigdatagenomics/utils#59]
Any chance we can get a spark 1.5 version published on maven central?  I changed the pom to 1.5.2 and all seemed well...

Thanks,

J

**Comment by fnothaft** [comment]
Hi!

Even though the current release is built against Spark 1.2, you should be OK using the latest release with Spark 1.5. Our build is set up so that Spark is not built in to the binaries (Spark is a user provided dependency), and all 1.x Spark releases _should_ be binary compatible. If you are seeing issues with Spark 1.5 though, let me know and I can take a look!

**Comment by heuermh** [comment]
To clarify, the dependency on Spark is provided scope
```xml
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.10</artifactId>
        <version>${spark.version}</version>
        <scope>provided</scope>
```
https://github.com/bigdatagenomics/utils/blob/master/pom.xml#L364

so it will pick up the Spark dependencies at runtime.  If you need a compile time dependency to a different version of Spark in code that depends on this, use e.g.
```xml
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.10</artifactId>
        <version>1.5.2</version>
        <scope>compile</scope>
```
in your pom.xml and it will override the provided scope dependency here.

**Comment by calvertj** [comment]
Thanks, I will double check my pom,

J

**Comment by fnothaft** [comment]
@calvertj is the issue you're running into something like https://github.com/bigdatagenomics/adam/issues/902? I'll try to get a fix in soon, bump the version of Spark that we test against to 1.5.0, and cut a new release.

**Comment by calvertj** [comment]
@fnothaft that's the one, I made a little test project to repro
https://github.com/calvertj/metricstest
Thanks!
J

**Comment by calvertj** [comment]
@fnothaft FYI: I just upped the spark version in the utils pom.xml to 1.5.2.  Then I built and installed locally'; my little test project ran fine.
https://github.com/calvertj/utils
