### ISSUE TITLE
Release script is missing push after scala 2.10 commit

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/utils#79]
See https://github.com/bigdatagenomics/utils/pull/78#issuecomment-242131722

**Comment by heuermh** [comment]
@fnothaft could you handle this as part of the 0.2.8 release?

**Comment by heuermh** [comment]
Or I suppose I could cut the release, let me know.

**Comment by heuermh** [comment]
If the 0.2.8. release process went ok, with the extra move to Spark 2.0 step, we should add those to the release script for 0.2.9.

**Comment by fnothaft** [comment]
> If the 0.2.8 release process went ok, with the extra move to Spark 2.0 step, we should add those to the release script for 0.2.9.

+1

I'm also thinking that I'll refactor the release script to move to the releasing from maintainance branch model.

**Comment by fnothaft** [comment]
Fixed by #87.
