### ISSUE TITLE
changing default artifactId: utils-parent-spark2_2.10

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/utils#84]
I see that the poms have utils-parent-spark2_2.10 as the artifactId. Are we moving upstream projects to spark2 or should this default to utils-parent_2.10 with the option to change to Spark 2 with move_to_spark_2.sh?

**Comment by fnothaft** [comment]
Ah, that's a bug with the release scripts. That should've gotten reset to remove the spark2 after running the release matrix. I'll fix that.
