### ISSUE TITLE
Moving IntervalRDD from Interval to ReferenceRegion

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/utils#85]
There are issues in IntervalRDD, specifically in the creation of the IntervalTree. These issues could be more easily resolved if we moved the IntervalTree and IntervalRDD from Interval to ReferenceRegion. This allows us to internally work with the referenceName. Are there any objections to this?

**Comment by fnothaft** [comment]
OOC, what are the issues and why would they be easier to resolve if we moved from `Interval` to `ReferenceRegion`. I originally thought it'd be useful to have the `IntervalTree` data structure upstream for doing the joins, but https://github.com/bigdatagenomics/adam/pull/1234 is ultimately not using that after all, so I lean towards your proposal, I'd just like to have more context.

**Comment by akmorrow13** [comment]
Ok great. After digging a little deeper I may be able to get away with keeping Interval as is.

**Comment by heuermh** [comment]
Is this still an issue?

**Comment by heuermh** [comment]
Closing as WontFix
