### ISSUE TITLE
Scoverage plugin not used properly

### ISSUE THREAD

**Issue by gslowikowski** [bigdatagenomics/utils#95]
Version `0.99.2` of Scoverage plugin was added in commit https://github.com/bigdatagenomics/utils/blob/26eb8bd14ff548f7212317ae83f9d42070ee26de on 24 Sep 2014.

Since version `1.0.0` the plugin was completely rewritten (I'm the author) and it should be used differently.

Instead of creating special profile and adding magic parameters to `scala-maven-plugin` you have to just run `mvn scoverage:report` (or any other plugin goal, there are many of them - read [usage section](https://github.com/scoverage/scoverage-maven-plugin/#how-to-use)).

And most important thing - remove `scalac-scoverage-plugin` from dependencies.

BTW, tle latest version of the plugin is `1.3.0`.

**Comment by heuermh** [comment]
@gslowikowski Thanks for the help!  We thought we resolved this downstream in https://github.com/bigdatagenomics/adam/issues/1124, will take a look here and in quinine.

**Comment by fnothaft** [comment]
Agreed, thanks for the help and the ping @gslowikowski (and most of all, thank you for writing a really useful plugin!). As @heuermh noted in his comment, we've resolved this in a downstream project but haven't propagated the fix to two of our other projects. We'll fix the plugin usage both here and downstream. Thanks again for checking in and for developing the plugin!

**Comment by fnothaft** [comment]
Agreed, thanks for the help and the ping @gslowikowski (and most of all, thank you for writing a really useful plugin!). As @heuermh noted in his comment, we've resolved this in a downstream project but haven't propagated the fix to two of our other projects. We'll fix the plugin usage both here and downstream. Thanks again for checking in and for developing the plugin!
