### ISSUE TITLE
IntervalRDD fails when underlying RDD is not sorted

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/utils#99]
If RDD is not sorted, IntervalPartition does not force sorting of ConcreteIntervalArray. RDD's should not have to be sorted for IntervalRDD to work (one may only want sorted partitions, not entire sorted RDD).

**Comment by fnothaft** [comment]
Ah, sorry, that's my bad. https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/rdd/IntervalPartition.scala#L107 should be changed to use the [apply method](https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala#L86) instead.

**Comment by fnothaft** [comment]
Let me know if you'd like me to make the fix.

**Comment by heuermh** [comment]
Is this still an issue?

**Comment by heuermh** [comment]
Fixed by #100
